# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2
      inputs:
        version: '3.0.x'
<<<<<<< HEAD
        
=======
>>>>>>> 4bc889d7aaba0113553bb7397350cfe3c79118d5

    - task: UseDotNet@2
      inputs:
        version: '2.2.x'
        packageType: runtime
<<<<<<< HEAD
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
=======
        performMultiLevelLookup: true
        
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
>>>>>>> 4bc889d7aaba0113553bb7397350cfe3c79118d5
